fluid-player/fluid-player

templates/default/styles.css
vast.js

Player shows current play time and video duration in 'default' template

---

fluidplayer.js

Avoid promise issues

---

fluidplayer.css

Reverts fluid-player/fluid-player#140

Revert " Ad marker css and logo tweaks"

---

fluidplayer.js

Like -0.1 opacity and 1.1 opacity in old browsers

Fix fadeOut/fadeIn opacity to correct values in the end of animation

---

fluidplayer.js

If context menu changed, fullscreenMode variable is incorrect

Fullscreen mode variable correct place

---

fluidplayer.css
fluidplayer.js

Reverts fluid-player/fluid-player#192

Revert "Theatre mode settable params"

---

fluidplayer.js

remove linebreaks from string https://stackoverflow.com/questions/10805125/how-to-remove-all-line-breaks-from-a-string

Edge source switch fix

---

fluidplayer.js

Possible values: contain, cover, auto
Reference to https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

Add poster image size option (posterImageSize)

---

fluidplayer.js

https://github.com/fluid-player/fluid-player/issues/319

add showPlayButton on ad

---

fluidplayer.js

https://github.com/fluid-player/fluid-player/issues/327

Add ability to change controls titles

---

fluidplayer.js

https://github.com/fluid-player/fluid-player/issues/329

 Fix multiple videos play

---

fluidplayer.js

added relevant html5 event listeners

---

fluidplayer.js

code error sending wrong parameter to function

---

fluidplayer.js

Add ability to unload Fluid Player somewhat gracefully. See #119

Add destroy function

---

src/modules/adsupport.js

Fix somehow misplaced condition that prevents from some controls being shown in normal mode.
Closes #454

Fix ad skip button not showing properly

---

src/fluidplayer.js
src/modules/streaming.js

1. Move HLS configuration to callbacks
2. Add DASH configuration
3. Add ability to configure XMLHttpRequest
Closes #464 
Closes #58

Config callbacks

---

src/fluidplayer.js
test/html/custom_context.tpl.html

1. Introduces custom context menu options
2. Allows to hide default controls in context menu
FP14

Custom context

---

src/fluidplayer.js
test/html/vod_basic_autohide.tpl.html

1. Small refactor to FP code related to inactivity handling.
Related #459

Small refactor, add auto-hide test case

---

src/fluidplayer.js
src/modules/cardboard.js
src/modules/vpaid.js
test/html/vod_extended.tpl.html

1. Fix issue with ended event not being fired
2. Deal with the looping issues in cardboard
3. Deal with post-roll triggering a loop of the video
Closes #414

Fix issues related to missing ended event

---

test/html/vod_reponsive.tpl.html

Introduces a small test case to test `fillToContainer`
Related #461

Responsive test case

---

src/fluidplayer.js
src/modules/streaming.js

1. Fix initialization error when options are undefined
2. Fix dash debug switch

Ensure options is object, fix dash debug

---

src/fluidplayer.js

Fixes https://github.com/fluid-player/fluid-player/issues/574

FP-145 [GitHub_574]_Overlay html over video (also in fullscreen)

---

src/fluidplayer.js

1. Allow customizing playbackRates in configuration
Closes #560

Allow customizing playbackRates

---

src/modules/miniplayer.js

Code review done in this pull request: https://github.com/fluid-player/fluid-player/pull/744

[Github_743] Failed to resolve import "cheerio/lib/api/traversing"

---

src/fluidplayer.js
src/modules/streaming.js
test/html/dash_live.tpl.html
test/html/dash_live_vast.tpl.html

FP-250 Preload doesn't work for .m3u8 files when the player is serving in-stream ads

---

src/fluidplayer.js
src/modules/miniplayer.js

Test site: https://fp-37.glitch.me
#404

FP-37 [GitHub #404] Lighthouse says: Does not use passive listeners to improve scrolling performance

---

src/modules/adsupport.js

FP-260 [GitHub_761] adClickable and CTA parameters don't work when 2 VAST ad is loaded

---

src/index.js
src/polyfills.js

1. Uses `globalThis` instead of `window` in index and polyfills
Relates to #787

Fluid Player doesn't work with Next.js

---

src/css/fluidplayer.css
src/fluidplayer.js

Reverts fluid-player/fluid-player#857

Revert "FP-254 Live Indicator"

---

src/modules/subtitles.js
src/modules/timeline.js

Set 'withCredentials' to false when requesting .vtt files

FP-426 Subtitle vtt files are requested with credentials
